### ISSUE TITLE
Error after typing `/test True`

### ISSUE THREAD

**Issue by LightD31** [hckdotng/n8n-nodes-discord#11]
This error is thrown when I type `/test True` or any other slash command

`RangeError [BitFieldInvalid]: Invalid bitfield flag or number: ADMINISTRATOR.
    at Function.resolve (/home/node/.n8n/nodes/node_modules/discord.js/src/util/BitField.js:168:11)
    at PermissionsBitField.has (/home/node/.n8n/nodes/node_modules/discord.js/src/util/BitField.js:60:28)
    at PermissionsBitField.has (/home/node/.n8n/nodes/node_modules/discord.js/src/util/PermissionsBitField.js:92:82)
    at Client.<anonymous> (/home/node/.n8n/nodes/node_modules/n8n-nodes-discord/nodes/Discord/bot/commands.ts:43:31)
    at Client.emit (node:events:525:35)
    at Client.emit (node:domain:489:12)
    at InteractionCreateAction.handle (/home/node/.n8n/nodes/node_modules/discord.js/src/client/actions/InteractionCreate.js:97:12)
    at Object.module.exports [as INTERACTION_CREATE] (/home/node/.n8n/nodes/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)
    at WebSocketManager.handlePacket (/home/node/.n8n/nodes/node_modules/discord.js/src/client/websocket/WebSocketManager.js:352:31)
    at WebSocketShard.onPacket (/home/node/.n8n/nodes/node_modules/discord.js/src/client/websocket/WebSocketShard.js:489:22)
    at WebSocketShard.onMessage (/home/node/.n8n/nodes/node_modules/discord.js/src/client/websocket/WebSocketShard.js:328:10)
    at callListener (/home/node/.n8n/nodes/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onMessage (/home/node/.n8n/nodes/node_modules/ws/lib/event-target.js:209:9)
    at WebSocket.emit (node:events:513:28)
    at WebSocket.emit (node:domain:489:12)
    at Receiver.receiverOnMessage (/home/node/.n8n/nodes/node_modules/ws/lib/websocket.js:1178:20)
    at Receiver.emit (node:events:513:28)
    at Receiver.emit (node:domain:489:12)
    at Receiver.dataMessage (/home/node/.n8n/nodes/node_modules/ws/lib/receiver.js:528:14)
    at Receiver.getData (/home/node/.n8n/nodes/node_modules/ws/lib/receiver.js:446:17)
    at Receiver.startLoop (/home/node/.n8n/nodes/node_modules/ws/lib/receiver.js:148:22)
    at Receiver._write (/home/node/.n8n/nodes/node_modules/ws/lib/receiver.js:83:10)
    at writeOrBuffer (node:internal/streams/writable:391:12)
    at _write (node:internal/streams/writable:332:10)
    at Receiver.Writable.write (node:internal/streams/writable:336:10)
    at TLSSocket.socketOnData (/home/node/.n8n/nodes/node_modules/ws/lib/websocket.js:1272:35)
    at TLSSocket.emit (node:events:513:28)
    at TLSSocket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
    at TLSWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
  code: 'BitFieldInvalid'
}`

**Comment by hckdotng** [comment]
Did you gave applications.commands permissions? https://raw.githubusercontent.com/hckdotng/n8n-nodes-discord/main/images/url-gen.png
