### ISSUE TITLE
ERROR: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by TheSmilez** [hckdotng/n8n-nodes-discord#9]
Hello again!

Lately I've been having issues with the buttons and interactions, today finding the error stated in title through the execution logs. It was working as it should for about a month but lately started having issues a couple of days ago. Maybe I'm just missing something that I haven't caught on my part, but I'd thought I'd share just in case anybody is having the same issue or if it's even an issue at all, haha. I've attached images of the workflow along under you will find my console logs as well. Cheers!

> ***NOTE:*** I have a separate workflow which shares the same principal in how it processes information to achieve the same goal (to delete all messages). That workflow is activated manually and seems to work just fine - So leads me to believe that it has to with the Discord API.

## **STACK ERRORS IN N8N**
```
TypeError: Cannot read properties of undefined (reading 'length')
    at Object.execute (C:\Users\alien\.n8n\nodes\node_modules\n8n-nodes-discord\nodes\Discord\DiscordTrigger.node.ts:158:25)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Workflow.runNode (C:\Users\alien\.n8n\node_modules\n8n-workflow\src\Workflow.ts:1270:19)
    at C:\Users\alien\.n8n\node_modules\n8n-core\src\WorkflowExecute.ts:939:29
```

## **CONSOLE ERRORS**
```
triggerWorkflow 8e9fa46d-b16c-4a85-b1f4-d40a1618c079
webhoooooook 8e9fa46d-b16c-4a85-b1f4-d40a1618c079
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
DiscordAPIError[40060]: Interaction has already been acknowledged.
    at SequentialHandler.runRequest (C:\Users\alien\.n8n\node_modules\@discordjs\rest\src\lib\handlers\SequentialHandler.ts:498:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at SequentialHandler.queueRequest (C:\Users\alien\.n8n\node_modules\@discordjs\rest\src\lib\handlers\SequentialHandler.ts:198:11)
    at REST.request (C:\Users\alien\.n8n\node_modules\@discordjs\rest\src\lib\REST.ts:343:20)
    at ButtonInteraction.deferUpdate (C:\Users\alien\.n8n\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:200:5)
Service path not specified, so defaulting to ipc.config.socketRoot + ipc.config.appspace + id
requested connection to  bot /tmp/app.bot
Connecting client on Unix Socket : /tmp/app.bot
## socket connection to server detected ##
dispatching event to  bot /tmp/app.bot
```

## **WORKFLOW**
![brave_hfOvFpX0u6](https://user-images.githubusercontent.com/52396069/208045199-13948844-bbff-4a18-8140-bd078bdc8e52.png)
![brave_nJ6Cdp4zQt](https://user-images.githubusercontent.com/52396069/208045201-3463d102-520d-472a-bc30-5e7caf04fa03.png)

**Comment by TheSmilez** [comment]
> My bad, I break something with the previous release, I pushed a fix on npm.

Seems to work now, many thanks!
